backend/models/User.php
<?php

namespace backend\models;

use Yii;

/**
 * This is the model class for table "user".
 *
 * @property integer $id
 * @property string $username
 * @property string $email
 * @property integer $status_email
 * @property string $password
 * @property string $activation
 * @property integer $status
 * @property string $auth_key
 * @property string $created_at
 * @property string $updated_at
 */
class User extends \yii\db\ActiveRecord
{
  /**
   * @inheritdoc
   */
  public static function tableName()
  {
    return 'user';
  }

  /**
   * @inheritdoc
   */
  public function rules()
  {
    return [
      [['status_email', 'status'], 'integer'],
      [['created_at', 'updated_at'], 'safe'],
      [['username', 'email', 'password', 'activation', 'auth_key'], 'string', 'max' => 255],
    ];
  }

  /**
   * @inheritdoc
   */
  public function attributeLabels()
  {
    return [
      'id' => 'ID',
      'username' => 'Username',
      'email' => 'Email',
      'status_email' => 'Status Email',
      'password' => 'Password',
      'activation' => 'Activation',
      'status' => 'Status',
      'auth_key' => 'Auth Key',
      'created_at' => 'Created At',
      'updated_at' => 'Updated At',
    ];
  }
}

backend/controllers/UsersController.php
<?php

namespace backend\controllers;

use common\models\Bills;
use common\models\Helpfunc;
use frontend\models\Balance;
use frontend\models\SignupForm;
use Yii;
use common\models\User;
use backend\models\UsersSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use frontend\models\Transfer;
use yii\data\Pagination;


/**
 * UsersController implements the CRUD actions for User model.
 */
class UsersController extends Controller
{
  /**
   * @inheritdoc
   */
  public function behaviors()
  {
    return [
      'access' => [
        'class' => AccessControl::className(),
        'rules' => [
          [
            'actions' => [
              'logout',
              'index',
              'create',
              'update',
              'delete',
              'view',
              'pay',
              'send',
            ],
            'allow' => true,
            'roles' => ['admin'],
          ],
        ],
      ],
      'verbs' => [
        'class' => VerbFilter::className(),
        'actions' => [
          'delete' => ['POST'],
        ],
      ],
    ];
  }

  /**
   * Lists all User models.
   * @return mixed
   */
  public function actionIndex()
  {

    $searchModel = new UsersSearch();
    $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

    return $this->render('index', [
      'searchModel' => $searchModel,
      'dataProvider' => $dataProvider,
    ]);
  }

  /**
   * Displays a single User model.
   * @param integer $id
   * @return mixed
   */
  public function actionView($id)
  {

//    $history = Bills::findOne(['user_from' => 1]);

//    Helpfunc::debug($history);
//    Helpfunc::debug($history->emailuser);

    $history = Bills::find()->where(['user_from' => $id])->orWhere(['user_to' => $id])->all();

//    Helpfunc::debug($history[0]->emailuser);
//    Helpfunc::debug($history[0]->emailuser);
    $history[0]->emailuserto;
    $history[0]->emailuserfrom;

    $active_str = '';

    foreach ($history as $row) {
//      Helpfunc::debug($row['emailuser'][0]['email']);
      $active_str .= '<tr><td>' . $row['emailuserfrom'][0]['email'] . '</td><td>' . $row['emailuserto'][0]['email'] . '</td><td>' . $row['scope'] . '</td><td>' . $row['balance_from'] . '</td></tr>';
    }

    if ($active_str == '') {
      $active_str .= '<tr><td>n/a</td><td>n/a</td><td>n/a</td><td>n/a</td></tr>';
    }

    return $this->render('view', [
      'model' => $this->findModel($id),
      'active_str' => $active_str,
    ]);
  }

  /**
   * Creates a new User model.
   * If creation is successful, the browser will be redirected to the 'view' page.
   * @return mixed
   */
  public function actionCreate()
  {
//    $model = new User();

    $model = new SignupForm();

    if ($model->load(Yii::$app->request->post()) && $model->validate()) {
      if ($user = $model->signup(1)) {

        $auth = Yii::$app->authManager;
        $userRole = $auth->getRole('user');
        $auth->assign($userRole, $user->getId());

        $score = new Balance();
        $score->id_user = $user->id;
        $score->balance = 0;
        $score->save();


        return $this->redirect(['/users']);
      } else {
        echo "невозможно добавить пользователя";
      }
    } else {
      return $this->render('create', [
        'model' => $model,
      ]);
    }
  }

  /**
   * Updates an existing User model.
   * If update is successful, the browser will be redirected to the 'view' page.
   * @param integer $id
   * @return mixed
   */
  public function actionUpdate($id)
  {
    $model = $this->findModel($id);

    if ($model->load(Yii::$app->request->post()) && $model->save()) {
      return $this->redirect(['view', 'id' => $model->id]);
    } else {
      return $this->render('update', [
        'model' => $model,
      ]);
    }
  }

  /**
   * Deletes an existing User model.
   * If deletion is successful, the browser will be redirected to the 'index' page.
   * @param integer $id
   * @return mixed
   */
  public function actionDelete($id)
  {
    $this->findModel($id)->delete();

    return $this->redirect(['index']);
  }


  public function actionPay($id)
  {
    $user = $this->findModel($id);
    $model = new Transfer();

    if ($model->load(Yii::$app->request->post()) && $model->validate()) {

      $user_to = User::findOne(['email' => $model->user_to]);
      $user_from = User::findOne(Yii::$app->user->id);

//      не хватает средств для перевода
      if ($model->scope > Yii::$app->user->identity->balance) {
        Yii::$app->session->setFlash('email_to_email_transfer', 'На вашем балансе не хватает средств для перевода');
      } elseif (Yii::$app->user->identity->email == $user_to->email) {
        Yii::$app->session->setFlash('email_to_email_transfer', 'Вы не можете отправить средства самому себе');
      } elseif ($user_to) {
        if ($transfer = $model->transfer_user(null, $user_to, $user_from)) {
          $transaction = Yii::$app->db->beginTransaction();
          try {
            if ($transfer->save() && $user_from->updateBalance(-$transfer->scope) && $user_to->updateBalance($transfer->scope)) {
              Yii::$app->session->setFlash('success_transfer', 'Перевод стредств выполнен успешно');
              $transaction->commit();
              $this->refresh();
            }
          } catch (\Throwable $e) {
            Yii::$app->session->setFlash('error_transfer', 'Ошибка при изменении балансов пользователей');
            $transaction->rollBack();
          }

        } else {
          Yii::$app->session->setFlash('error_transfer', 'Ошибка при переводе стредств');
        }
      } else {
        Yii::$app->session->setFlash('error_transfer', "Пользователь с таким Email не найден");
      }
    }

    $username = $user->username;
    $email = $user->email;

    return $this->render('translationToTheUser', compact('username', 'email', 'model'));
  }


  public function actionSend($id)
  {
    $user = $this->findModel($id);
    $model = new Transfer();

    if ($model->load(Yii::$app->request->post()) && $model->validate()) {

      $user_from = User::findOne($id);
      $user_to = User::findOne(['email' => $model->user_to]);

      if ($model->scope > $user_from->getBalance()) {
        Yii::$app->session->setFlash('error_transfer', 'На балансе пользователя не хватает средств для перевода');
      } elseif ($user_to->email == $user_from->email) {
        Yii::$app->session->setFlash('error_transfer', 'Адрес отправления совпадает с адресом получения');
      } elseif ($user_to && $user_from) {
        if ($transfer = $model->transfer_user(Yii::$app->user->id, $user_to, $user_from)) {

          $transaction = Yii::$app->db->beginTransaction();
          try {
            if ($transfer->save() && $user_from->updateBalance(-$model->scope) && $user_to->updateBalance($model->scope)) {
              Yii::$app->session->setFlash('success_transfer', 'Перевод стредств выполнен успешно');

              $transaction->commit();
              $this->refresh();
            }
          } catch (\Throwable $e) {
            Yii::$app->session->setFlash('error_transfer', 'Ошибка при изменении балансов пользователей');
            $transaction->rollBack();
          }

        } else {
          Yii::$app->session->setFlash('error_transfer', 'Ошибка при переводе стредств');
        }
      } else {
        Yii::$app->session->setFlash('error_transfer', 'Невозможно найти отправителя/получателя');
      }

    }

    $username = $user->username;
    $email = $user->email;

    return $this->render('send', compact('username', 'email', 'model'));
  }

  /**
   * Finds the User model based on its primary key value.
   * If the model is not found, a 404 HTTP exception will be thrown.
   * @param integer $id
   * @return User the loaded model
   * @throws NotFoundHttpException if the model cannot be found
   */
  protected
  function findModel($id)
  {
    if (($model = User::findOne($id)) !== null) {
      return $model;
    } else {
      throw new NotFoundHttpException('The requested page does not exist.');
    }
  }
}

frontend/controllers/UserController.php
<?php
/**
 * Created by PhpStorm.
 * User: chvs
 * Date: 30.10.2017
 * Time: 1:20
 */

namespace frontend\controllers;

use frontend\models\Balance;
use frontend\models\Transfer;
use Yii;
use yii\web\Controller;
use common\models\Bills;
use common\models\Helpfunc;
use common\models\User;

class UserController extends Controller
{

  public function actionIndex()
  {
    return $this->render('index');
  }


  public function actionHistory()
  {
    $query = Bills::find()->where(["user_from" => Yii::$app->user->identity->id])->asArray()->all();

    $active_str = '';

    foreach ($query as $row) {
      $active_str .= '<tr><td>' . $row['user_from'] . '</td><td>' . $row['user_to'] . '</td><td>' . $row['scope'] . '</td><td>' . $row['balance_from'] . '</td></tr>';
    }

    if ($active_str == '') {
      $active_str .= '<tr><td>n/a</td><td>n/a</td><td>n/a</td><td>n/a</td></tr>';
    }

    return $this->render('history', [
      'active_str' => $active_str,
    ]);

  }


  public function actionTransfer()
  {
    $model = new Transfer();

    if ($model->load(Yii::$app->request->post()) && $model->validate()) {
//      не хватает средств для перевода
      if ($model->scope > Yii::$app->user->identity->balance) {
        Yii::$app->session->setFlash('email_to_email_transfer', 'На вашем балансе не хватает средств для перевода');
      } else {
        $user_to = User::findOne(['email' => $model->user_to]);
        $balance_to = Balance::findOne(["id_user" => $user_to->id]);

//      перевод самому себе
        if (Yii::$app->user->identity->email == $user_to->email) {
          Yii::$app->session->setFlash('email_to_email_transfer', 'Вы не можете отправить средства самому себе');
        } else {

//        перевод другому пользователю, если пользователь найден
          if ($user_to) {
            if ($transfer = $model->transfer()) {

              $user_from = Balance::findOne(["id_user" => $transfer->user_from]);
              $user_from->updateBalance(-$transfer->scope);
              $balance_to->updateBalance($transfer->scope);

//          Применение изменений к БД
              $transaction = Yii::$app->db->beginTransaction();
              try {
                if ($transfer->save() && $user_from->save() && $balance_to->save()) {
                  Yii::$app->session->setFlash('success_transfer', 'Перевод стредств выполнен успешно');
                  $transaction->commit();
                }
              } catch (\Throwable $e) {
                Yii::$app->session->setFlash('error_user_transfer', 'Ошибка при изменении балансов пользователей');
                $transaction->rollBack();
              }

            } else {
              Yii::$app->session->setFlash('error_transfer', 'Ошибка при переводе стредств');
            }

          } else {
            Yii::$app->session->setFlash('no_email_transfer', "Пользователь с таким Email не найден");
          }

        }
      }
    }

    return $this->render('transfer', compact("model"));
  }

}

frontend/views/user/history.php
<h1>История счета</h1>

<table class="history-bills">
  <tr>
    <th>От куда</th>
    <th>Куда</th>
    <th>Перевод, руб</th>
    <th>Текущий баланс, руб</th>
  </tr>
  <?= $active_str ?>
</table>

frontend/views/user/index.php
<?php

use yii\helpers\Html;
use common\models\Helpfunc;

?>


<div class="wraper">
  <h2>Личный кабинет</h2>

  <?php

  if (\Yii::$app->user->can('user')) {
    echo "<p> Привет Юзер </p>";
  } elseif (\Yii::$app->user->can('admin'))
  {
    echo "<p> Привет Админ </p>";
  } else {
    echo "<p> Ты не Юзер </p>";
  }


//  $user = \common\models\User::findOne(1);

//  $user = \common\models\User::find()->where(['id' => 1])->all();

//  Helpfunc::debug($user);
//  Helpfunc::debug(count($user[0]->billsfrom));
//  Helpfunc::debug(count($user[0]->billsto));
//  Helpfunc::debug($user[0]->billsfrom);
//  Helpfunc::debug($user[0]->billsto);
//  echo '<pre>'. print_r($user, true) .'</pre>';

  ?>

  <?= Html::a('Просмотреть историю счета', ['/user/history'], ['class' => 'custom-button long-button'])?>
  <?= Html::a('Перевести средства другому пользователю', ['/user/transfer'], ['class' => 'custom-button long-button'])?>
  <?= Html::a('Удалить аккаунт', ['#'], ['class' => 'custom-button long-button js-button-campaign'])?>

</div>

<!--<h2>Личный кабинет</h2>-->

frontend/views/user/transfer.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */

/* @var $model \frontend\models\SignupForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Перевод средств';
$this->params['breadcrumbs'][] = $this->title;

?>


<?php if (Yii::$app->session->hasFlash('success_transfer')) : ?>
  <div class="alert alert-success alert-dismissable alert-registr">
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
    <?= Yii::$app->session->getFlash('success_transfer') ?>
  </div>
<?php endif; ?>

<?php if (Yii::$app->session->hasFlash('error_user_transfer')) : ?>
  <div class="alert alert-danger alert-dismissable alert-registr">
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
    <?= Yii::$app->session->getFlash('error_user_transfer') ?>
  </div>
<?php endif; ?>

<?php if (Yii::$app->session->hasFlash('email_to_email_transfer')) : ?>
  <div class="alert alert-danger alert-dismissable alert-registr">
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
    <?= Yii::$app->session->getFlash('email_to_email_transfer') ?>
  </div>
<?php endif; ?>

<?php if (Yii::$app->session->hasFlash('no_email_transfer')) : ?>
  <div class="alert alert-danger alert-dismissable alert-registr">
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
    <?= Yii::$app->session->getFlash('no_email_transfer') ?>
  </div>
<?php endif; ?>

<?php if (Yii::$app->session->hasFlash('error_transfer')) : ?>
  <div class="alert alert-danger alert-dismissable alert-registr">
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
    <?= Yii::$app->session->getFlash('error_transfer') ?>
  </div>
<?php endif; ?>

<div class="site-signup">
  <h2>Перевод средств другому пользователю</h2>

  <p>Пожалуйста, заполните следующие поля для перевода средств:</p>

  <div class="row">
    <div class="col-lg-5">
      <?php $form = ActiveForm::begin(['id' => 'form-signup']); ?>

      <?= $form->field($model, 'user_to')->textInput(['autofocus' => true]) ?>

      <?= $form->field($model, 'scope') ?>

      <div class="form-group">
        <?= Html::submitButton('Подтвердить', ['class' => 'btn btn-primary', 'name' => 'signup-button']) ?>
      </div>

      <?php ActiveForm::end(); ?>
    </div>
  </div>
</div>